---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configmap-aggregator-example
  namespace: default
  labels:
    app: configmap-aggregator-example
spec:
  selector:
    matchLabels:
      app: configmap-aggregator-example
  template:
    metadata:
      labels:
        app: configmap-aggregator-example
    spec:
      containers:
      - name: configmap-aggregator
        image: quay.io/bakins/configmap-aggregator:0.1.0
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
